name: CD

on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+

jobs:

  shared-cd:
    name: Shared CD

    defaults:
      run:
        working-directory: shared

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # last version
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run build

  web-app-cd:
    name: Web App CD
    needs:
      - shared-cd

    defaults:
      run:
        working-directory: web-app

    env:
      # Firebase Configuration
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}

      # Firebase Functions API
      FIREBASE_FUNCTIONS_URL: ${{ secrets.FIREBASE_FUNCTIONS_URL }}

      # Rates API
      RATES_API_URL: ${{ secrets.RATES_API_URL }}

      # IEX API
      IEX_API_URL: ${{ secrets.IEX_API_URL }}
      IEX_PUBLISHABLE_TOKEN: ${{ secrets.IEX_PUBLISHABLE_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # last version
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: web-app-dist
          path: web-app/dist
          retention-days: 1

  firebase-cd:
    name: Firebase CD
    needs:
      - shared-cd
      - web-app-cd

    defaults:
      run:
        working-directory: firebase

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: web-app-dist
          path: firebase/dist
      - uses: actions/setup-node@v2
        with:
          # last version
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm ci
        working-directory: firebase/functions
      - run: npm install -g firebase-tools
      - run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
