name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 10

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clean install of dependencies
        run: npm ci
        working-directory: functions
      - name: Run checks
        run: npm run check
        working-directory: functions
      - name: Test build
        run: npm run build
        working-directory: functions
      - name: Create coverage report
        run: npm run coverage
        working-directory: functions
      - name: Push coverage report to Coveralls
        uses: coverallsapp/github-action@master
        with:
          base-path: functions
          github-token: ${{ secrets.GITHUB_TOKEN }}
